
<TextIdentifier
	xmlns:cws="http://schemas.cordys.com/cws/1.0"
	type="com.cordys.translation.TextIdentifier"
	typeVersion="55890f21-u239-76j6-988a-92j7opq6ws09"
	RuntimeDocumentID="005056A2-7798-A1E8-A637-0F3C60AE0111">
	<DocumentID>005056A2-7798-A1E8-A637-0F3C60ADC111</DocumentID>
	<Name>005056A2-7798-A1E8-A637-0F3C60ADC111</Name>
	<Description>Catch Exception</Description>
	<CreatedBy>sysadmin</CreatedBy>
	<CreationDate>2018-08-05T18:22:46.189</CreationDate>
	<Notes/>
	<DefaultText>Catch Exception</DefaultText>
	<TranslationInformation>
		<uri
			id="005056A2-27FA-A1E8-A29B-E2ADE61A0130"
		/>
	</TranslationInformation>
	<Translations>
		<uri
			id="005056A2-7798-A1E8-A637-0F3C60AE4111"
		/>
	</Translations>
</TextIdentifier>
